version: '2'

services:
  mosquitto:
    image: maoqide/mosquitto-alpine
    restart: always
    network_mode: bridge
    ports:
     - "1883:1883"

  mqtt-light:
    image: localtest/mqtt-light
    privileged: true
    restart: always
    network_mode: bridge
    depends_on:
    - mosquitto
    environment:
     - GPIO_PIN=17
     - MQTT_BROKER=192.168.10.245
     - MQTT_TOPIC=laser-light
     - MQTT_PORT=1883
     - MQTT_KEEPALIVE_INTERVAL=60

  mqtt-led:
    image: localtest/mqtt-laser
    privileged: true
    restart: always
    network_mode: bridge
    depends_on:
     - mqtt-light
    environment:
     - GPIO_PIN=21
     - MQTT_BROKER=192.168.10.245
     - MQTT_TOPIC=laser-light
     - MQTT_PORT=1883
     - MQTT_KEEPALIVE_INTERVAL=60
